### ISSUE TITLE
Web Administration: Search functionality

### ISSUE THREAD

**Issue by kiran002** [amitjoy/feature-flags-for-osgi#18]
**Note:** This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [x] feature request

* **What is the current behavior?**

Currently all the features/strategies/groups are displayed in a static table. As the list of features gets bigger, the features would be hard to visualize.

* **What is the expected behavior?**

It would be nice to group features, search functionality. This would definitely increase maintainability of the web administration module. 

* **What is the motivation / use case for changing the behavior?**

Increased ease of use/ readability/ maintainability.

**Comment by amitjoy** [comment]
closing since this issue is now invalid
